---
title: "Isabelle Sanchez - Statistician Engineer"
output: 
  html_document:
   logo: img/Logotype-INRAE.jpg
   number_sections: false
   css: style.css
   includes:
     before_body: extlogo.html
---


I am a statistician engineer at [INRAE](https://www.inrae.fr/) in [MISTEA](https://www6.montpellier.inrae.fr/mistea/) lab. 

I analyze data of alcoholic fermentations, phenotyping (plants, animals), survey etc... and develop R packages and web applications.

## Contact information

**UMR Mistea**, building 21 3rd floor, office 319, 2 place Pierre Viala, 34060 Montpellier Cedex 2, France

Isabelle.Sanchez _at_ inrae.fr / +33 (0)4 99 61 31 95
    
https://github.com/sanchezi

# Projects Phenome, EPPN2020, COEX, Starwine, TechCare, Vinid'Occ

* Detection of outliers (on spatial data, on temporal data, impulsed noised outliers ...)
* Biclustering on survey data
* Spatial clustering on survey data
* GAM modeling on temporal data

# Development of neural networks and deep learning workflows in R (Tensorflow, Keras)

* Approximate Bayesian Computation and Convolutional NN
* workflows on images, time series for regression or classification predictions
* Numerical simulations or applications on Lake temporal data
* Tools: Tensorflow and Keras in R but also [Flux](https://fluxml.ai/Flux.jl/stable/) in Julia

# Development for high throughput phenotyping data, temporal and spatial:

* data management and visualization of experiments in greenhouses or fields
* methods for detecting outliers
* [openSilexStatR](https://sanchezi.github.io/openSilexStatR/) - [github repository](https://github.com/sanchezi/openSilexStatR)
* [statgenHTP](https://CRAN.R-project.org/package=statgenHTP)

# Development of R packages for web service client for high throughput phenotyping platforms

* opensilex-ws-client-R
* **phisWSClientR**: https://github.com/OpenSILEX/opensilexClientR, https://github.com/OpenSILEX/phisWSClientR

# Development of R packages of statistical methods developed within the lab:

* geozoning ([on Github](https://github.com/hazaeljones/geozoning))
* bliss ([on Github](https://github.com/pmgrollemund/bliss), [on CRAN](https://CRAN.R-project.org/package=bliss))
* spiceFP ([on Github](https://github.com/giraultg/SpiceFP), [on CRAN](https://CRAN.R-project.org/package=SpiceFP))
* blockmodels4inventories([on Gitlab](https://forgemia.inra.fr/nicolas.verzelen/blockmodels4inventories), [web site](nicolas.verzelen.pages.mia.inra.fr/blockmodels4inventories/))
* kfino ([on Gitlab](https://forgemia.inra.fr/isabelle.sanchez/kfino),[on CRAN](https://cran.r-project.org/package=kfino))

# Leading an R and Python programming working group

with a bit of Julia on the side...

[Gitlab repository](https://forgemia.inra.fr/gdtpyr/GdT-PyR)

[PyR blog](https://gdtpyr.pages.mia.inra.fr/blog/)

# Development of R/Shiny applications, shiny, shinydashboard, R server

Beta user in the [SK8](https://sk8.inrae.fr/) project. [documentation](https://docs.sk8.inrae.fr/)

[ORIOLE](https://oriole.sk8.inrae.fr/): A web application for the automatic filtering of outliers in databases produced by the Walk-over-Weighing (WoW) platform (TechCare project)
